version: '3.8'
services:
  zookeeper:
    image: strimzi/kafka:0.14.0-kafka-2.1.1
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
  kafka:
    image: strimzi/kafka:0.14.0-kafka-2.1.1
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties \
            --override listeners=$${KAFKA_LISTENERS} \
            --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} \
            --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} \
            --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME} \
            --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "8083:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka